import { Camp, SavedCamp, SUMMER_WEEKS } from "./types";

function weeksToSchedules(
  weekIndices: number[],
  startTime: string | null = "9:00 AM",
  endTime: string | null = "3:00 PM",
  earlyDropOff: string | null = null,
  latePickup: string | null = null
) {
  return weekIndices.map((i) => ({
    id: `sched-${i}-${Math.random().toString(36).slice(2, 8)}`,
    label: `Week of ${SUMMER_WEEKS[i].label}`,
    startDate: SUMMER_WEEKS[i].start,
    endDate: SUMMER_WEEKS[i].end,
    startTime,
    endTime,
    earlyDropOff,
    latePickup,
  }));
}

export const MOCK_CAMPS: Camp[] = [
  {
    id: "c1",
    slug: "aerial-cirque-over-denver",
    name: "Aerial Cirque Over Denver",
    description:
      "Camps are for ages 6-teen. This is a beginner/intermediate aerial camp perfect for those brand new to aerial or with less than a year of aerial experience. In the week long camp your kiddo will learn technique and skills on 4 apparatuses: silks, trapeze, hoop, sling. All our instructors are certified and have experience teaching youth aerialists — our focus is on safety and fun!",
    notes:
      "Learn aerial silks, trapeze, hoop, and hammock. There are half day camp options and full day camp options.",
    campType: "SUMMER_DAY",
    category: "SPORTS",
    websiteUrl: "https://aerialcirqueoverdenver.com/aerial-camps/",
    interestingDetails: "Aerial arts heavy — silks, trapeze, hoop, sling",
    city: "Denver",
    region: null,
    neighborhood: "Central Park",
    address: "4605 Quebec St. Denver, CO 80216",
    latitude: 39.7735,
    longitude: -104.9013,
    lunchIncluded: false,
    registrationOpenDate: null,
    registrationOpenTime: null,
    registrationStatus: "OPEN",
    dataConfidence: "VERIFIED",
    ageGroups: [
      {
        id: "ag1",
        label: "Ages 6-teen",
        minAge: 6,
        maxAge: 17,
        minGrade: 0,
        maxGrade: 12,
      },
    ],
    schedules: [
      ...weeksToSchedules(
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
        "9:00 AM",
        "3:00 PM"
      ),
    ],
    pricing: [
      {
        id: "p1a",
        label: "Full Day",
        amount: 300,
        unit: "PER_WEEK",
        durationWeeks: null,
        ageQualifier: null,
        discountNotes: null,
      },
      {
        id: "p1b",
        label: "Half Day (AM or PM)",
        amount: 175,
        unit: "PER_WEEK",
        durationWeeks: null,
        ageQualifier: null,
        discountNotes: null,
      },
    ],
  },
  {
    id: "c2",
    slug: "denver-parks-rec-summer-in-the-parks",
    name: "Denver Parks & Rec — Summer in the Parks",
    description:
      "The Denver Parks and Recreation Summer in the Parks program offers affordable, full-summer day camp experiences across multiple Denver park locations. Activities include sports, arts and crafts, field trips, swimming, and more. Lunches are provided at select locations.",
    notes:
      "Incredibly economical option. City Park location runs 9:30-3:30. Some locations (like Swansea) extend hours and provide lunches. A beloved Denver tradition for families.",
    campType: "SUMMER_DAY",
    category: "MULTI_ACTIVITY",
    websiteUrl: "https://www.denvergov.org/Government/Agencies-Departments-Offices/Parks-Recreation",
    interestingDetails: "Full summer enrollment — one of the best deals in Denver",
    city: "Denver",
    region: null,
    neighborhood: "City Park",
    address: "2001 Colorado Blvd, Denver, CO 80205",
    latitude: 39.7506,
    longitude: -104.9535,
    lunchIncluded: true,
    registrationOpenDate: "2026-03-15",
    registrationOpenTime: "9:00 AM",
    registrationStatus: "COMING_SOON",
    dataConfidence: "VERIFIED",
    ageGroups: [
      {
        id: "ag2a",
        label: "Ages 5-12",
        minAge: 5,
        maxAge: 12,
        minGrade: 0,
        maxGrade: 6,
      },
    ],
    schedules: weeksToSchedules(
      [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      "9:30 AM",
      "3:30 PM",
      null,
      "4:30 PM"
    ),
    pricing: [
      {
        id: "p2",
        label: "Full Summer",
        amount: 550,
        unit: "FLAT",
        durationWeeks: 11,
        ageQualifier: null,
        discountNotes: "Denver resident discount available",
      },
    ],
  },
  {
    id: "c3",
    slug: "avid4-adventure-camp-blue-sky",
    name: "Avid4 Adventure — Camp Blue Sky",
    description:
      "Camp Blue Sky is a sleepaway camp in the foothills outside Denver for grades 1-5. Campers spend their days hiking, mountain biking, rock climbing, paddling, and exploring the Colorado wilderness. Small group sizes ensure personalized attention and skill building in a supportive outdoor environment.",
    notes: "One and two week options available. Located in Evergreen, CO.",
    campType: "SLEEPAWAY",
    category: "NATURE",
    websiteUrl: "https://avid4.com/mt-evans-camps",
    interestingDetails: "Hiking, mountain biking, rock climbing, paddling",
    city: "Evergreen",
    region: "Denver Metro",
    neighborhood: "Evergreen",
    address: "Evergreen, CO",
    latitude: 39.6333,
    longitude: -105.3172,
    lunchIncluded: true,
    registrationOpenDate: null,
    registrationOpenTime: null,
    registrationStatus: "OPEN",
    dataConfidence: "VERIFIED",
    ageGroups: [
      {
        id: "ag3",
        label: "Grades 1-5",
        minAge: 6,
        maxAge: 11,
        minGrade: 1,
        maxGrade: 5,
      },
    ],
    schedules: weeksToSchedules([0, 1, 2, 3, 4, 5, 6, 7, 8], null, null),
    pricing: [
      {
        id: "p3a",
        label: "1 Week",
        amount: 1349,
        unit: "PER_CAMP",
        durationWeeks: 1,
        ageQualifier: null,
        discountNotes: "Sibling and early bird discounts available",
      },
      {
        id: "p3b",
        label: "2 Weeks",
        amount: 2399,
        unit: "PER_CAMP",
        durationWeeks: 2,
        ageQualifier: null,
        discountNotes: null,
      },
    ],
  },
  {
    id: "c4",
    slug: "cheley-colorado-camps",
    name: "Cheley Colorado Camps",
    description:
      "Cheley Colorado Camps has been a premier summer camp experience in Estes Park since 1921. Nestled in the Rocky Mountains at 8,000 feet, campers enjoy horseback riding, backpacking, rock climbing, fly fishing, and evening campfires. A transformative 27-day wilderness experience for ages 9-17.",
    notes: "One of Colorado's most prestigious sleepaway camps. Book early — fills fast.",
    campType: "SLEEPAWAY",
    category: "NATURE",
    websiteUrl: "https://www.cheley.com/about/rates",
    interestingDetails: "Horseback riding, backpacking, rock climbing, fly fishing",
    city: "Estes Park",
    region: "Northern Colorado",
    neighborhood: "Estes Park",
    address: "Estes Park, CO",
    latitude: 40.3772,
    longitude: -105.5217,
    lunchIncluded: true,
    registrationOpenDate: null,
    registrationOpenTime: null,
    registrationStatus: "OPEN",
    dataConfidence: "VERIFIED",
    ageGroups: [
      {
        id: "ag4a",
        label: "8 year olds (1-week intro)",
        minAge: 8,
        maxAge: 8,
        minGrade: 2,
        maxGrade: 3,
      },
      {
        id: "ag4b",
        label: "Ages 9-17 (27-day camp)",
        minAge: 9,
        maxAge: 17,
        minGrade: 3,
        maxGrade: 12,
      },
    ],
    schedules: [
      {
        id: "s4a",
        label: "First Term",
        startDate: "2026-06-10",
        endDate: "2026-07-06",
        startTime: null,
        endTime: null,
        earlyDropOff: null,
        latePickup: null,
      },
      {
        id: "s4b",
        label: "Second Term",
        startDate: "2026-07-08",
        endDate: "2026-08-03",
        startTime: null,
        endTime: null,
        earlyDropOff: null,
        latePickup: null,
      },
    ],
    pricing: [
      {
        id: "p4a",
        label: "Intro Week (8 yr olds)",
        amount: 1250,
        unit: "PER_CAMP",
        durationWeeks: 1,
        ageQualifier: "8 year olds",
        discountNotes: null,
      },
      {
        id: "p4b",
        label: "1-Week (Ages 9-10)",
        amount: 1600,
        unit: "PER_CAMP",
        durationWeeks: 1,
        ageQualifier: "9-10 year olds",
        discountNotes: null,
      },
      {
        id: "p4c",
        label: "27-Day Term",
        amount: 7450,
        unit: "PER_CAMP",
        durationWeeks: 4,
        ageQualifier: "Ages 9-17",
        discountNotes: "Financial assistance available",
      },
    ],
  },
  {
    id: "c5",
    slug: "altitude-all-sports",
    name: "Altitude All Sports — Multi-Sport Camp",
    description:
      "Altitude All Sports is dedicated to developing your child's basic athletic skills through a series of fun drills and games. Rotating through traditional sports curriculums, participants will have the opportunity to develop various essential sports skills and lay the groundwork for future athletic competition. During the age of technology, now more than ever, it is so important to encourage healthy physical activity.",
    notes: "Different weeks for different ages — check schedule carefully.",
    campType: "SUMMER_DAY",
    category: "SPORTS",
    websiteUrl: "https://altitudeallsports.com/",
    interestingDetails: "Multi-sport rotation: basketball, soccer, flag football, baseball",
    city: "Denver",
    region: null,
    neighborhood: "Central Park",
    address: "Central Park, Denver, CO",
    latitude: 39.7652,
    longitude: -104.8948,
    lunchIncluded: false,
    registrationOpenDate: null,
    registrationOpenTime: null,
    registrationStatus: "OPEN",
    dataConfidence: "VERIFIED",
    ageGroups: [
      {
        id: "ag5",
        label: "Ages 4-12",
        minAge: 4,
        maxAge: 12,
        minGrade: -1,
        maxGrade: 6,
      },
    ],
    schedules: weeksToSchedules([0, 1, 2, 3, 5, 6, 7, 8, 9], "9:00 AM", "12:00 PM"),
    pricing: [
      {
        id: "p5",
        label: "Per Week",
        amount: 225,
        unit: "PER_WEEK",
        durationWeeks: null,
        ageQualifier: null,
        discountNotes: "Multi-week discount available",
      },
    ],
  },
  {
    id: "c6",
    slug: "code-ninjas-denver",
    name: "Code Ninjas — Summer Tech Camp",
    description:
      "Code Ninjas summer camps teach kids to code by building video games and apps. Each week features a different theme — from Minecraft modding to Roblox game development to robotics with Arduino. Kids learn real programming concepts in a fun, game-based environment. No prior coding experience needed.",
    notes: "Each week is a different theme. Kids keep their projects.",
    campType: "SUMMER_DAY",
    category: "STEM",
    websiteUrl: "https://www.codeninjas.com/",
    interestingDetails: "Minecraft modding, Roblox dev, robotics, game design",
    city: "Denver",
    region: null,
    neighborhood: "Cherry Creek",
    address: "250 Fillmore St, Denver, CO 80206",
    latitude: 39.7188,
    longitude: -104.9556,
    lunchIncluded: false,
    registrationOpenDate: "2026-02-01",
    registrationOpenTime: null,
    registrationStatus: "OPEN",
    dataConfidence: "VERIFIED",
    ageGroups: [
      {
        id: "ag6",
        label: "Ages 7-14",
        minAge: 7,
        maxAge: 14,
        minGrade: 1,
        maxGrade: 8,
      },
    ],
    schedules: weeksToSchedules(
      [1, 2, 3, 5, 6, 7, 8, 9],
      "9:00 AM",
      "4:00 PM",
      "8:00 AM",
      null
    ),
    pricing: [
      {
        id: "p6",
        label: "Per Week",
        amount: 350,
        unit: "PER_WEEK",
        durationWeeks: null,
        ageQualifier: null,
        discountNotes: "10% early bird discount before April 1",
      },
    ],
  },
  {
    id: "c7",
    slug: "denver-art-museum-creative-camps",
    name: "Denver Art Museum — Creative Summer Camps",
    description:
      "Explore creativity through painting, sculpture, printmaking, and mixed media at the Denver Art Museum's summer camps. Each week is inspired by current exhibitions and the museum's permanent collection. Campers work with professional teaching artists in the museum's dedicated studio spaces.",
    notes: "Museum admission included. Showcase for parents on Friday afternoons.",
    campType: "SUMMER_DAY",
    category: "ARTS",
    websiteUrl: "https://denverartmuseum.org/",
    interestingDetails: "Painting, sculpture, printmaking inspired by real exhibitions",
    city: "Denver",
    region: null,
    neighborhood: "Capitol Hill",
    address: "100 W 14th Ave Pkwy, Denver, CO 80204",
    latitude: 39.7372,
    longitude: -104.9893,
    lunchIncluded: false,
    registrationOpenDate: "2026-03-01",
    registrationOpenTime: "10:00 AM",
    registrationStatus: "OPEN",
    dataConfidence: "PLACEHOLDER",
    ageGroups: [
      {
        id: "ag7a",
        label: "Ages 5-8",
        minAge: 5,
        maxAge: 8,
        minGrade: 0,
        maxGrade: 3,
      },
      {
        id: "ag7b",
        label: "Ages 9-12",
        minAge: 9,
        maxAge: 12,
        minGrade: 3,
        maxGrade: 6,
      },
    ],
    schedules: weeksToSchedules([0, 1, 2, 3, 5, 6, 7], "9:30 AM", "3:30 PM"),
    pricing: [
      {
        id: "p7a",
        label: "Members",
        amount: 275,
        unit: "PER_WEEK",
        durationWeeks: null,
        ageQualifier: null,
        discountNotes: "Museum membership required for member pricing",
      },
      {
        id: "p7b",
        label: "Non-Members",
        amount: 325,
        unit: "PER_WEEK",
        durationWeeks: null,
        ageQualifier: null,
        discountNotes: null,
      },
    ],
  },
  {
    id: "c8",
    slug: "rocky-mountain-nature-explorers",
    name: "Rocky Mountain Nature Explorers",
    description:
      "Get your kids outside and exploring Colorado's incredible natural world. Campers hike local trails, learn about native plants and wildlife, practice wilderness skills, and develop a deep appreciation for the outdoors. Weekly themes include geology, bird watching, water ecology, and survival skills.",
    notes: "Outdoor camp — kids should come prepared for weather. Snacks provided.",
    campType: "SUMMER_DAY",
    category: "NATURE",
    websiteUrl: "https://example.com/nature-explorers",
    interestingDetails: "Hiking, wildlife study, wilderness skills, water ecology",
    city: "Denver",
    region: null,
    neighborhood: "Wash Park",
    address: "South Marion Pkwy, Denver, CO 80209",
    latitude: 39.6977,
    longitude: -104.9746,
    lunchIncluded: false,
    registrationOpenDate: "2026-04-01",
    registrationOpenTime: null,
    registrationStatus: "COMING_SOON",
    dataConfidence: "PLACEHOLDER",
    ageGroups: [
      {
        id: "ag8",
        label: "Ages 6-13",
        minAge: 6,
        maxAge: 13,
        minGrade: 0,
        maxGrade: 7,
      },
    ],
    schedules: weeksToSchedules(
      [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
      "8:30 AM",
      "3:00 PM",
      null,
      "5:00 PM"
    ),
    pricing: [
      {
        id: "p8",
        label: "Per Week",
        amount: 285,
        unit: "PER_WEEK",
        durationWeeks: null,
        ageQualifier: null,
        discountNotes: "Sibling discount: 15% off second child",
      },
    ],
  },
  {
    id: "c9",
    slug: "denver-center-performing-arts-camps",
    name: "Denver Center for the Performing Arts — Theater Camp",
    description:
      "Young performers take the stage at the Denver Center for the Performing Arts. Campers learn acting, improvisation, voice, and movement from professional theater artists. Each week culminates in a showcase performance for family and friends. Builds confidence, creativity, and collaboration skills.",
    notes: "Performance showcase every Friday at 2 PM. Costumes provided.",
    campType: "SUMMER_DAY",
    category: "THEATER",
    websiteUrl: "https://www.denvercenter.org/education/",
    interestingDetails: "Acting, improv, voice, movement — Friday showcase performances",
    city: "Denver",
    region: null,
    neighborhood: "Capitol Hill",
    address: "1101 13th St, Denver, CO 80204",
    latitude: 39.7393,
    longitude: -104.9983,
    lunchIncluded: false,
    registrationOpenDate: "2026-02-15",
    registrationOpenTime: null,
    registrationStatus: "OPEN",
    dataConfidence: "VERIFIED",
    ageGroups: [
      {
        id: "ag9a",
        label: "Ages 7-11",
        minAge: 7,
        maxAge: 11,
        minGrade: 1,
        maxGrade: 5,
      },
      {
        id: "ag9b",
        label: "Ages 12-17",
        minAge: 12,
        maxAge: 17,
        minGrade: 6,
        maxGrade: 12,
      },
    ],
    schedules: weeksToSchedules([0, 1, 2, 3, 5, 6, 7, 8], "10:00 AM", "4:00 PM"),
    pricing: [
      {
        id: "p9",
        label: "Per Week",
        amount: 395,
        unit: "PER_WEEK",
        durationWeeks: null,
        ageQualifier: null,
        discountNotes: "Need-based scholarships available",
      },
    ],
  },
  {
    id: "c10",
    slug: "tiny-chefs-cooking-camp",
    name: "Tiny Chefs — Kids Cooking Camp",
    description:
      "Tiny Chefs brings the kitchen to life for young cooks! Each week features a different cuisine theme — Italian, Mexican, Japanese, French pastry, and more. Kids learn real cooking techniques, knife skills (age-appropriate), food safety, and nutrition. They bring home recipes and a full meal they prepared.",
    notes: "All dietary restrictions accommodated. Ingredients and apron included.",
    campType: "SUMMER_DAY",
    category: "COOKING",
    websiteUrl: "https://example.com/tiny-chefs",
    interestingDetails: "Global cuisine themes — Italian, Mexican, Japanese, French pastry",
    city: "Denver",
    region: null,
    neighborhood: "Highlands",
    address: "3500 Navajo St, Denver, CO 80211",
    latitude: 39.7619,
    longitude: -105.0148,
    lunchIncluded: true,
    registrationOpenDate: "2026-03-01",
    registrationOpenTime: null,
    registrationStatus: "WAITLIST",
    dataConfidence: "VERIFIED",
    ageGroups: [
      {
        id: "ag10a",
        label: "Ages 5-8 (Little Chefs)",
        minAge: 5,
        maxAge: 8,
        minGrade: 0,
        maxGrade: 2,
      },
      {
        id: "ag10b",
        label: "Ages 9-14 (Junior Chefs)",
        minAge: 9,
        maxAge: 14,
        minGrade: 3,
        maxGrade: 8,
      },
    ],
    schedules: weeksToSchedules([1, 2, 3, 5, 6, 7], "9:00 AM", "1:00 PM"),
    pricing: [
      {
        id: "p10",
        label: "Per Week",
        amount: 310,
        unit: "PER_WEEK",
        durationWeeks: null,
        ageQualifier: null,
        discountNotes: null,
      },
    ],
  },
];

export const MOCK_SAVED_CAMPS: SavedCamp[] = [
  {
    id: "sc1",
    campId: "c1",
    camp: MOCK_CAMPS[0],
    notes: "Cecilia wants to try this!",
    savedAt: "2026-02-20T10:00:00Z",
    notifyEmail: true,
    notifyPush: false,
    notifySms: false,
  },
  {
    id: "sc2",
    campId: "c2",
    camp: MOCK_CAMPS[1],
    notes: null,
    savedAt: "2026-02-22T14:30:00Z",
    notifyEmail: true,
    notifyPush: true,
    notifySms: false,
  },
  {
    id: "sc3",
    campId: "c6",
    camp: MOCK_CAMPS[5],
    notes: "Check if they have Minecraft week in July",
    savedAt: "2026-03-01T09:15:00Z",
    notifyEmail: true,
    notifyPush: false,
    notifySms: false,
  },
];
